### ISSUE TITLE
Uncaught exception

### ISSUE THREAD

**Issue by CodeArtist1** [mistakster/jquery-daterange#6]
Hello, I love this date range picker.  It works wonderfully on all my uses except for this one page.  I am using Jquery 1.10.2 and Jquery UI 1.10.3.

If I clear the date range form the field and click outside the field, then select it again, the datepicker then works.  Here is the error that I get from JQuery: 

---

uncaught exception: Invalid date
focus()jquery....min.js (line 6)
i = "yy-mm-dd"
a = "2014-04-31"
s = undefined
storeLastDateRange()jquery...ange.js (line 58)
dateText = ["2014-04-01", "2014-04-31"]
dateFormat = "yy-mm-dd"
beforeShow()jquery...ange.js (line 69)
input = input#daterange_chart.hasDatepicker 2014-04-...14-04-31✉
inst = Object { id="daterange_chart", input={...}, selectedDay=0, more...}
focus()jquery....min.js (line 6)
t = input#daterange_chart.hasDatepicker 2014-04-...14-04-31✉
hasData()jquery....min.js (line 5)
e = Object { originalEvent=Event focus, type="focus", timeStamp=0, more...}
(?)()javasc...void(0) (line 5)
e = focus
## ...Hash(this)),this.containers[t].containerCache.over&&(this.containers[t]._trigger...

Any ideas as to why this would happen?
thanks

.

**Comment by mistakster** [comment]
Hello!

I think, it happens because you entered wrong date into text field. jQuery UI Datepicker cannot parse “2014-04-31” (April has only 30 days) and throws this exception.

I have no solution how to handle such situations. Probably, you can disable text editing in this field. Or you can validate value on “keyup” and “blur” events and not allow user enter wrong dates.

Hope this makes sense.

**Comment by CodeArtist1** [comment]
Please disregard my issue above, I was setting an invalid date in my PHP script.  Dumb mistake.

**Comment by mistakster** [comment]
Okay. Feel free to contact me if you will face to any other issues.
